version: '3.8'

services:
#  mysql:
#    image: mysql:8.0
#    container_name: mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: best_solutions_db
#    ports:
#      - '3306:3306'
#    volumes:
#      - mysql-data:/var/lib/mysql
#      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
#    networks:
#      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '8080:80'
    depends_on:
      - mysql
    networks:
      - app-network

#  backend:
#    build:
#      context: .
#      dockerfile: docker/Dockerfile.backend
#    container_name: back-app
#    depends_on:
#      - mysql
#    environment:
#      DATABASE_HOST: mysql
#      DATABASE_PORT: 3306
#      DATABASE_USER: root
#      DATABASE_PASSWORD: root
#      DATABASE_NAME: best_solutions_db
#    ports:
#      - '3000:3000'
#    networks:
#      - app-network

#  frontend:
#    build:
#      context: .
#      dockerfile: docker/Dockerfile.frontend
#    container_name: front-app
#    ports:
#      - '4000:4000'
#    depends_on:
#      - backend
#    networks:
#      - app-network
#
  frontend-backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend-backend
    container_name: frontend-backend
    ports:
      - '3000:3000'
      - '4000:4000'
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: best_solutions_db
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
