# Используем официальный образ Node.js версии 20.14
FROM node:20.14

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы package.json и package-lock.json
COPY ./ ./

# Устанавливаем зависимости
RUN npm ci

# Собираем билд
RUN npm run build-ssr:front

# Открываем порты для приложения
EXPOSE 4000

# Команда для запуска скрипта
CMD ["node", "dist/apps/front-app/server/main.js"]
