# Используем официальный образ Node.js версии 20.14
FROM node:20.14

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем файлы проекта
COPY ./dist ./dist

# Открываем порты для приложения
EXPOSE 3000
EXPOSE 4000

# Копируем скрипт запуска
COPY ./start.sh /app/start.sh
RUN chmod +x /app/start.sh

# Команда для запуска скрипта
CMD ["/app/start.sh"]
