# Используем официальный образ Node.js версии 20.14
FROM node:20.14

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы проекта
COPY ./dist ./dist

# Открываем порт для Node.js
EXPOSE 4000

# Команда для запуска приложения
CMD ["node", "dist/apps/front-app/server/main.js"]
