# Используем официальный образ Node.js версии 20.14
FROM node:20.14

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы package.json и package-lock.json
COPY ./ ./

# Устанавливаем зависимости
RUN npm ci

# Собираем билд
RUN npm run build:back

# Открываем порты для приложения
EXPOSE 3000

# Команда для запуска скрипта
CMD ["node", "dist/apps/back-app/main.js"]
