# Используем официальный образ Node.js версии 20.14
FROM node:20.14

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы package.json и package-lock.json
COPY ./ ./

# Устанавливаем зависимости
RUN npm ci

# Собираем билд build:back
RUN npm run build:back

# Собираем билд build:back
RUN npm run build-ssr:front

# Откройте порты 3000 и 4000
EXPOSE 3000
EXPOSE 4000

# Команда для запуска скрипта
RUN npm run server:start
