# Используем официальный образ Node.js версии 20.14
FROM node:20.14

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем файлы проекта
COPY ./dist/apps/back-app ./back-app

# Открываем порты для приложения
EXPOSE 3000

# Команда для запуска скрипта
CMD ["node", "back-app/main.js"]
