name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Pull Docker image
        run: docker pull node:20.14

      - name: Run build inside Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app node:20.14 sh -c "npm i && npm run build-ssr:front"

      - name: Check build result
        run: |
          if [ -d "dist/apps/front-app/browser" ]; then
             echo "Build completed successfully."
           else
             echo "Build failed [front-app/browser]."
             exit 1
           fi

            if [ -d "dist/apps/front-app/server" ]; then
             echo "Build completed successfully."
           else
             echo "Build failed [front-app/server]."
             exit 1
           fi

           if [ -d "dist/apps/back-app" ]; then
             echo "Build completed successfully."
           else
             echo "Build failed [back-app]."
             exit 1
           fi
