name: Deploy

on:
  push:
    branches:
      - release
  pull_request:
    types:
      - closed
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Clone repository and switch to release branch
        run: |
          ssh -o StrictHostKeyChecking=no -p 22 root@185.244.50.198 << 'EOF'
            DEPLOY_DIR="$HOME/bs-angular-nest-nx"

            cd bs-angular-nest-nx

            git fetch
            git checkout release
            git pull origin release

            docker-compose down
            docker-compose up --build -d

          EOF
